apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo # has to match .spec.template.metadata.labels
  serviceName: "demo"
  replicas: 4 # by default is 1
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: demo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      hostAliases:
      - ip: "172.31.106.149"
        hostnames:
        - "db"
      containers:
      - name: nginx-proxy
        image: jwilder/nginx-proxy
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: demo-data
          mountPath: /etc/nginx/certs
          subPath: ssl_certs
        - mountPath: /tmp/docker.sock
          name: docker-sock
          readOnly: true
        env:
        - name: DEFAULT_HOST
          value: "demo-pos.magestore.com"
      - name: magento-c226-mvp
        image: httpd:2.4
        imagePullPolicy: Always
        volumeMounts:
        - name: demo-data
          mountPath: /var/www/html
          subPath: magento_c226_mvp
        env:
        - name: CERT_NAME
          value: comodo
        - name: HTTPS_METHOD
          value: noredirect
        - name: VIRTUAL_HOST
          value: demo-pos.magestore.com
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-data
      - name: docker-sock
        hostPath:
          # location on host
          path: /var/run/docker.sock
          # this field is optional
          type: File
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
