# create a job init magento
# The job copy base magento data to /var/www/html
apiVersion: batch/v1
kind: Job
metadata:
  name: init-magento
spec:
  template:
    metadata:
      name: init-magento
    spec:
      containers:
      - name: magento
        image: magestore/magento:2.2.6
        command: ["cp"]
        args: ["-rpf", "/var/www/html/.", "/data/"]
        volumeMounts:
        - name: demo-data
          mountPath: "/data"
          subPath: magento_c226_mvp
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-data
      restartPolicy: Never
