apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo # has to match .spec.template.metadata.labels
  serviceName: "demo"
  replicas: 4 # by default is 1
  template:
    metadata:
      labels:
        app: demo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-proxy
        image: jwilder/nginx-proxy
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: demo-data
          mountPath: /etc/nginx/certs
          subPath: ssl_certs
        - mountPath: /tmp/docker.sock
          name: docker-sock
          readOnly: true
        env:
        - name: DEFAULT_HOST
          value: "demo-pos.magestore.com"
      volumes:
      - name: demo-data
        # This AWS EBS volume must already exist.
        awsElasticBlockStore:
          volumeID: vol-072ef3cefcb87261f
          fsType: ext4
      - name: docker-sock
        hostPath:
          # location on host
          path: /var/run/docker.sock
          # this field is optional
          type: File
