apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    # Enable PROXY protocol
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    # Ensure the ELB idle timeout is less than nginx keep-alive timeout. By default,
    # NGINX keep-alive is set to 75s. If using WebSockets, the value will need to be
    # increased to '3600' to avoid any potential issues.
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-proxy-protocol: "true"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - demo.magestore.com
    secretName: comodo-secret
  rules:
  - host: demo.magestore.com
    http:
      paths:
      - path: /
        backend:
          serviceName: demo-pos-mvp
          servicePort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: demo-pos-mvp
spec:
  selector:
    app: demo-pos-mvp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-pos-mvp
spec:
  selector:
    matchLabels:
      app: demo-pos-mvp # has to match .spec.template.metadata.labels
  serviceName: "demo-pos-mvp"
  replicas: 4 # by default is 1
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: demo # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      hostAliases:
      - ip: "172.31.106.149"
        hostnames:
        - "db"
      - name: c226-mvp
        image: magestore/magento:2.2.6
        imagePullPolicy: Always
        volumeMounts:
        - name: demo-data
          mountPath: /var/www/html
          subPath: magento_c226_mvp
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-data
      - name: docker-sock
        hostPath:
          # location on host
          path: /var/run/docker.sock
          # this field is optional
          type: File
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
