# create a job init magento
# The job copy base magento data to /var/www/html
apiVersion: batch/v1
kind: Job
metadata:
  name: init-magento
spec:
  backoffLimit: 1
  template:
    metadata:
      name: job-init-magento
    spec:
      containers:
      #- name: magento-c226
      #  image: magestore/magento:2.2.6
      #  command: ["cp"]
      #  args: ["-rpf", "/var/www/html/.", "/var/www/src/"]
      #  volumeMounts:
      #  - name: demo-data
      #    mountPath: "/var/www/src"
      #    subPath: magento_c226_src
      #- name: magento-c226-mvp
      #  image: magestore/magento:2.2.6-mvp
      #  command: ["cp"]
      #  args: ["-rpf", "/var/www/html/.", "/data/"]
      #  volumeMounts:
      #  - name: demo-data
      #    mountPath: "/data"
      #    subPath: magento_c226_mvp
      - name: magento-c226-aus
        image: magestore/magento:2.2.6-aus
        command:
        - "sh"
        - "-c"
        - >
          cp -dRf /var/www/src/. /var/www/aus/ ;
          cp -dRf /var/www/html/. /var/www/aus/ ;
        volumeMounts:
        - name: demo-data
          mountPath: "/var/www/aus"
          subPath: magento_c226_aus
        - name: demo-data
          mountPath: "/var/www/src"
          subPath: magento_c226_src
      - name: magento-c226-omc
        image: magestore/magento:2.2.6-omc
        command:
        - "sh"
        - "c"
        - >
          cp -dRf /var/www/src/. /var/www/omc/ ;
          cp -dRf /var/www/html/. /var/www/omc/ ;
        volumeMounts:
        - name: demo-data
          mountPath: "/var/www/omc"
          subPath: magento_c226_omc
        - name: demo-data
          mountPath: "/var/www/src"
          subPath: magento_c226_src
      
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-nfs
      restartPolicy: Never
