# create a job init magento
# The job copy base magento data to /var/www/html
apiVersion: batch/v1
kind: Job
metadata:
  name: init-magento
spec:
  template:
    metadata:
      name: job-init-magento
    spec:
      containers:
      #- name: magento-2.2.6-mvp
      #  image: magestore/magento:2.2.6-mvp
      #  command: ["cp"]
      #  args: ["-rpf", "/var/www/html/.", "/data/"]
      #  volumeMounts:
      #  - name: demo-data
      #    mountPath: "/data"
      #    subPath: magento_c226_mvp
      - name: magento-2.2.6-aus
        image: magestore/magento:2.2.6-aus
        command: ["cp"]
        args: ["-rpf", "/var/www/html/.", "/data/"]
        volumeMounts:
        - name: demo-data
          mountPath: "/data"
          subPath: magento_c226_aus
      - name: magento-2.2.6-omc
        image: magestore/magento:2.2.6-omc
        command: ["cp"]
        args: ["-rpf", "/var/www/html/.", "/data/"]
        volumeMounts:
        - name: demo-data
          mountPath: "/data"
          subPath: magento_c226_omc
      - name: magento-2.2.6
        image: magestore/magento:2.2.6
        command: ["cp"]
        args: ["-rpf", "/var/www/html/.", "/data/"]
        volumeMounts:
        - name: demo-data
          mountPath: "/data"
          subPath: magento_c226_src
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-nfs
      restartPolicy: Never
