apiVersion: batch/v1
kind: Job
metadata:
  name: init-magento-c226-mvp
spec:
  backoffLimit: 1
  template:
    metadata:
      name: job-init-magento-c226-mvp
    spec:
      containers:
      - name: magento-c226-mvp
        image: magestore/magento:2.2.6-mvp
        command:
        - "sh"
        - "-c"
        - >
          cp -dRf /var/www/src/. /var/www/mvp/ ;
          cp -dRf /var/www/html/. /var/www/mvp/ ;
        volumeMounts:
        - name: demo-data
          mountPath: "/var/www/mvp"
          subPath: magento_c226_mvp
        - name: demo-data
          mountPath: "/var/www/src"
          subPath: magento_c226_src
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-nfs
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-magento-c226-aus
spec:
  backoffLimit: 1
  template:
    metadata:
      name: job-init-magento-c226-aus
    spec:
      containers:
      - name: magento-c226-aus
        image: magestore/magento:2.2.6-aus
        command:
        - "sh"
        - "-c"
        - >
          cp -dRf /var/www/src/. /var/www/aus/ ;
          cp -dRf /var/www/html/. /var/www/aus/ ;
        volumeMounts:
        - name: demo-data
          mountPath: "/var/www/aus"
          subPath: magento_c226_aus
        - name: demo-data
          mountPath: "/var/www/src"
          subPath: magento_c226_src
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-nfs
      restartPolicy: Never
---
# create a job init magento
# The job copy base magento data to /var/www/html
apiVersion: batch/v1
kind: Job
metadata:
  name: init-magento-c226-omc
spec:
  backoffLimit: 1
  template:
    metadata:
      name: job-init-magento-c226-omc
    spec:
      containers:
      - name: magento-c226-omc
        image: magestore/magento:2.2.6-omc
        command:
        - "sh"
        - "-c"
        - >
          cp -dRf /var/www/src/. /var/www/omc/ ;
          cp -dRf /var/www/html/. /var/www/omc/ ;
        volumeMounts:
        - name: demo-data
          mountPath: "/var/www/omc"
          subPath: magento_c226_omc
        - name: demo-data
          mountPath: "/var/www/src"
          subPath: magento_c226_src
      
      volumes:
      - name: demo-data
        persistentVolumeClaim:
          claimName: demo-nfs
      restartPolicy: Never
