apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 100.96.2.4
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
